export const Skills = () => {
  return (
    <ul>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/javascript.png"
          alt="JavaScript"
        />
        <span>JavaScript</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/typescript.png"
          alt="TypeScript"
        />
        <span>TypeScript</span>
      </li>
      <li>
        <img
          src="https://static-00.iconduck.com/assets.00/nextjs-icon-512x512-y563b8iq.png"
          alt="Next.js"
        />
        <span>Next.js</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/react-native.png"
          alt="React"
        />
        <span>React</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/redux.png"
          alt="Redux"
        />
        <span>Redux</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/material-ui.png"
          alt="MUI (Material-UI)"
        />
        <span>MUI / Material-UI</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/html-5.png"
          alt="HTML5"
        />
        <span>HTML5</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/css3.png"
          alt="CSS3 (including SCSS)"
        />
        <span>CSS3 / SASS</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/nodejs.png"
          alt="Node.js"
        />
        <span>Node.js</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/express.png"
          alt="Express"
        />
        <span>Express</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/mongodb.png"
          alt="MongoDB"
        />
        <span>MongoDB</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/mongoose.png"
          alt="Mongoose"
        />
        <span>Mongoose</span>
      </li>
      <li>
        <img
          src="https://img.icons8.com/color/48/000000/webpack.png"
          alt="Webpack"
        />
        <span>Webpack</span>
      </li>
      <li>
        <img src="https://img.icons8.com/color/48/000000/git.png" alt="Git" />
        <span>Git</span>
      </li>
    </ul>
  );
};
